#include <setup_wifi.h>

// code giao diện html
const char *html_page_2 = 
"<!doctype html>\n"
"<html lang=\"vi\">\n"
"	<head>\n"
"		<meta charset=\"UTF-8\" />\n"
"		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"		<title>EVsafe - Onboarding</title>\n"
"		<style>\n"
"			* {\n"
"				margin: 0;\n"
"				padding: 0;\n"
"				box-sizing: border-box;\n"
"			}\n"
"\n"
"			body {\n"
"				font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
"				height: 100vh;\n"
"				overflow: hidden;\n"
"			}\n"
"\n"
"			.container {\n"
"				position: relative;\n"
"				width: 428px;\n"
"				height: 926px;\n"
"				margin: 0 auto;\n"
"				background: linear-gradient(to bottom, #ffffff, #d4e2ff);\n"
"			}\n"
"\n"
"			/* Header Section */\n"
"			.header-container {\n"
"				position: absolute;\n"
"				top: 114px;\n"
"				left: 50%;\n"
"				transform: translateX(-50%);\n"
"				width: 396px;\n"
"				text-align: center;\n"
"			}\n"
"\n"
"			.logo-section {\n"
"				margin-bottom: 20px;\n"
"			}\n"
"\n"
"			.logo {\n"
"				font-size: 48px;\n"
"				font-weight: bold;\n"
"				color: #363636;\n"
"				margin-bottom: 8px;\n"
"			}\n"
"\n"
"			.title {\n"
"				font-size: 24px;\n"
"				font-weight: 600;\n"
"				color: #484848;\n"
"			}\n"
"\n"
"			/* WiFi List Container */\n"
"			.wifi-list-container {\n"
"				position: absolute;\n"
"				top: 250px;\n"
"				left: 50%;\n"
"				transform: translateX(-50%);\n"
"				width: 396px;\n"
"			}\n"
"\n"
"			.scan-button-container {\n"
"				text-align: center;\n"
"				margin-bottom: 16px;\n"
"			}\n"
"\n"
"			.scan-button {\n"
"				background: #4a90e2;\n"
"				color: white;\n"
"				border: none;\n"
"				border-radius: 8px;\n"
"				padding: 12px 24px;\n"
"				font-size: 16px;\n"
"				cursor: pointer;\n"
"				font-family: 'Be Vietnam Pro', sans-serif;\n"
"				font-weight: 500;\n"
"				display: inline-flex;\n"
"				align-items: center;\n"
"				gap: 8px;\n"
"			}\n"
"\n"
"			.scan-button:hover {\n"
"				background: #357abd;\n"
"			}\n"
"\n"
"            .wifi-list {\n"
"                background: rgba(255, 255, 255, 0.95);\n"
"                backdrop-filter: blur(2.5px);\n"
"                border-radius: 20px;\n"
"                padding: 16px;\n"
"                width: 100%;\n"
"                max-height: 450px;\n"
"                overflow-y: auto; \n"
"               -webkit-overflow-scrolling: touch;\n" 
"            }\n"
"\n"
"			.wifi-item {\n"
"				display: flex;\n"
"				justify-content: space-between;\n"
"				align-items: center;\n"
"				padding: 12px 8px;\n"
"				border-bottom: 1px solid rgba(255, 255, 255, 0.5);\n"
"				margin-bottom: 8px;\n"
"				cursor: pointer;\n"
"				transition: background-color 0.2s;\n"
"				border-radius: 8px;\n"
"			}\n"
"\n"
"			.wifi-item:last-child {\n"
"				border-bottom: none;\n"
"				margin-bottom: 0;\n"
"			}\n"
"\n"
"			.wifi-item:hover {\n"
"				background-color: rgba(0, 0, 0, 0.05);\n"
"			}\n"
"\n"
"			.wifi-name {\n"
"				font-family: 'Be Vietnam Pro', sans-serif;\n"
"				font-weight: 500;\n"
"				font-size: 16px;\n"
"				color: #484848;\n"
"				line-height: 22px;\n"
"			}\n"
"\n"
"			.wifi-icons {\n"
"				display: flex;\n"
"				gap: 8px;\n"
"				align-items: center;\n"
"			}\n"
"\n"
"			/* Signal strength bars */\n"
"			.signal-bars {\n"
"				display: flex;\n"
"				align-items: flex-end;\n"
"				gap: 2px;\n"
"				width: 20px;\n"
"				height: 16px;\n"
"			}\n"
"\n"
"			.signal-bar {\n"
"				background-color: #ccc;\n"
"				width: 3px;\n"
"				border-radius: 1px;\n"
"			}\n"
"\n"
"			.signal-bar.active {\n"
"				background-color: #4a90e2;\n"
"			}\n"
"\n"
"			.signal-bar-1 { height: 4px; }\n"
"			.signal-bar-2 { height: 7px; }\n"
"			.signal-bar-3 { height: 10px; }\n"
"			.signal-bar-4 { height: 13px; }\n"
"			.signal-bar-5 { height: 16px; }\n"
"\n"
"			/* Home Indicator */\n"
"			.home-indicator {\n"
"				position: absolute;\n"
"				bottom: 0;\n"
"				left: 0;\n"
"				right: 0;\n"
"				height: 25px;\n"
"			}\n"
"\n"
"			.home-indicator-bar {\n"
"				position: absolute;\n"
"				bottom: 10px;\n"
"				left: 50%;\n"
"				transform: translateX(-50%);\n"
"				width: 148px;\n"
"				height: 5px;\n"
"				background: rgba(255, 255, 255, 0.15);\n"
"				border-radius: 109.744px;\n"
"			}\n"
"\n"
"			/* Popup Styles */\n"
"			.popup-overlay {\n"
"				position: fixed;\n"
"				top: 0;\n"
"				left: 0;\n"
"				width: 100%;\n"
"				height: 100%;\n"
"				background-color: rgba(0, 0, 0, 0.5);\n"
"				display: none;\n"
"				justify-content: center;\n"
"				align-items: center;\n"
"				z-index: 1000;\n"
"			}\n"
"\n"
"			.popup-content {\n"
"				background: white;\n"
"				border-radius: 16px;\n"
"				padding: 24px;\n"
"				width: 320px;\n"
"				max-width: 90%;\n"
"				box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);\n"
"			}\n"
"\n"
"			.popup-header {\n"
"				margin-bottom: 20px;\n"
"			}\n"
"\n"
"			.popup-title {\n"
"				font-family: 'Be Vietnam Pro', sans-serif;\n"
"				font-weight: 600;\n"
"				font-size: 18px;\n"
"				color: #484848;\n"
"				margin-bottom: 8px;\n"
"			}\n"
"\n"
"			.popup-subtitle {\n"
"				font-family: 'Be Vietnam Pro', sans-serif;\n"
"				font-size: 14px;\n"
"				color: #888;\n"
"			}\n"
"\n"
"			.popup-form {\n"
"				margin-bottom: 20px;\n"
"			}\n"
"\n"
"			.popup-input {\n"
"				width: 100%;\n"
"				padding: 12px 16px;\n"
"				border: 2px solid #e6e6e6;\n"
"				border-radius: 8px;\n"
"				font-size: 16px;\n"
"				font-family: 'Be Vietnam Pro', sans-serif;\n"
"				box-sizing: border-box;\n"
"			}\n"
"\n"
"			.popup-input:focus {\n"
"				outline: none;\n"
"				border-color: #4a90e2;\n"
"			}\n"
"\n"
"			.popup-buttons {\n"
"				display: flex;\n"
"				gap: 12px;\n"
"			}\n"
"\n"
"			.popup-button {\n"
"				flex: 1;\n"
"				padding: 12px;\n"
"				border: none;\n"
"				border-radius: 8px;\n"
"				font-size: 16px;\n"
"				font-family: 'Be Vietnam Pro', sans-serif;\n"
"				font-weight: 500;\n"
"				cursor: pointer;\n"
"				transition: background-color 0.2s;\n"
"			}\n"
"\n"
"			.popup-button.cancel {\n"
"				background: #f5f5f5;\n"
"				color: #666;\n"
"			}\n"
"\n"
"			.popup-button.cancel:hover {\n"
"				background: #e6e6e6;\n"
"			}\n"
"\n"
"			.popup-button.connect {\n"
"				background: #4a90e2;\n"
"				color: white;\n"
"			}\n"
"\n"
"			.popup-button.connect:hover {\n"
"				background: #357abd;\n"
"			}\n"
"		</style>\n"
"	</head>\n"
"	<body>\n"
"		<div class=\"container\">\n"
"			<!-- Header Section -->\n"
"			<div class=\"header-container\">\n"
"				<div class=\"logo-section\">\n"
"					<div class=\"logo\">EVsafe</div>\n"
"					<div class=\"title\">Thiết lập WiFi</div>\n"
"				</div>\n"
"			</div>\n"
"\n"
"			<!-- WiFi List -->\n"
"			<div class=\"wifi-list-container\">\n"
"				<div class=\"scan-button-container\">\n"
"					<button class=\"scan-button\" onclick=\"scanWifiNetworks()\">\n"
"						🔄 Quét lại WiFi\n"
"					</button>\n"
"				</div>\n"
"				<div class=\"wifi-list\" id=\"wifiList\">\n"
"					<div style=\"text-align: center; padding: 20px; color: #888;\">\n"
"						Nhấn \"Quét lại WiFi\" để tìm mạng\n"
"					</div>\n"
"				</div>\n"
"			</div>\n"
"\n"
"			<!-- Home Indicator -->\n"
"			<div class=\"home-indicator\">\n"
"				<div class=\"home-indicator-bar\"></div>\n"
"			</div>\n"
"		</div>\n"
"\n"
"		<!-- WiFi Password Popup -->\n"
"		<div id=\"wifiPopup\" class=\"popup-overlay\">\n"
"			<div class=\"popup-content\">\n"
"				<div class=\"popup-header\">\n"
"					<div class=\"popup-title\" id=\"popupTitle\">Kết nối WiFi</div>\n"
"					<div class=\"popup-subtitle\" id=\"popupSubtitle\">Nhập mật khẩu để kết nối</div>\n"
"				</div>\n"
"				<div class=\"popup-form\">\n"
"					<input type=\"password\" class=\"popup-input\" id=\"wifiPassword\" placeholder=\"Nhập mật khẩu WiFi\" autocomplete=\"off\" />\n"
"                     <span \n"
"                      style=\"position: absolute; right: 85px; top: 50%; transform: translateY(-50%); cursor: pointer;\"\n"
"                      onclick=\"const p=document.getElementById(\'wifiPassword\'); p.type = p.type === \'password\' ? \'text\' : \'password\'; this.textContent = p.type === \'password\' ?\'🐵\' : \'🙈\';\"\n"
"                     >\n"
"                     🐵\n"
"                     </span>\n"
"				</div>\n"
"				<div class=\"popup-buttons\">\n"
"					<button class=\"popup-button cancel\" onclick=\"closeWifiPopup()\">Hủy</button>\n"
"					<button class=\"popup-button connect\" onclick=\"connectWifi()\">Kết nối</button>\n"
"				</div>\n"
"			</div>\n"
"		</div>\n"
"\n"
"		<script>\n"
"			// WiFi networks data\n"
"			let wifiNetworks = []\n"
"			let selectedWifi = null\n"
"\n"
"			// Scan WiFi networks from ESP32\n"
"			async function scanWifiNetworks() {\n"
"				const wifiList = document.getElementById('wifiList')\n"
"				wifiList.innerHTML = '<div style=\"text-align: center; padding: 20px; color: #888;\">Đang quét WiFi...</div>'\n"
"\n"
"				try {\n"
"					const response = await fetch('/scan')\n"
"					const networks = await response.json()\n"
"\n"
"					if (networks.length === 0) {\n"
"						wifiList.innerHTML = '<div style=\"text-align: center; padding: 20px; color: #888;\">Không tìm thấy mạng WiFi nào</div>'\n"
"						return\n"
"					}\n"
"\n"
"					// Update global networks data\n"
"					wifiNetworks = networks\n"
"					generateWifiList()\n"
"				} catch (error) {\n"
"					console.error('Scan failed:', error)\n"
"					wifiList.innerHTML = '<div style=\"text-align: center; padding: 20px; color: #ff6b6b;\">Quét WiFi thất bại. Hãy thử quét lại.</div>'\n"
"				}\n"
"			}\n"
"\n"
"			// Generate signal strength bars\n"
"			function getSignalBars(strength) {\n"
"				let barsHtml = '<div class=\"signal-bars\">'\n"
"				for (let i = 1; i <= 5; i++) {\n"
"					const activeClass = i <= strength ? 'active' : ''\n"
"					barsHtml += `<div class=\"signal-bar signal-bar-${i} ${activeClass}\"></div>`\n"
"				}\n"
"				barsHtml += '</div>'\n"
"				return barsHtml\n"
"			}\n"
"\n"
"			// Generate WiFi list from JSON data\n"
"			function generateWifiList() {\n"
"				const wifiList = document.getElementById('wifiList')\n"
"				wifiList.innerHTML = ''\n"
"\n"
"				wifiNetworks.forEach((network) => {\n"
"					const wifiItem = document.createElement('div')\n"
"					wifiItem.className = 'wifi-item'\n"
"					wifiItem.onclick = () => openWifiPopup(network)\n"
"\n"
"					const lockIcon = network.hasPassword ? '<span style=\"font-size: 14px;\">🔒</span>' : ''\n"
"					const signalBars = getSignalBars(network.signalStrength || 3)\n"
"\n"
"					wifiItem.innerHTML = `\n"
"						<p class=\"wifi-name\">${network.ssid || network.name}</p>\n"
"						<div class=\"wifi-icons\">\n"
"							${lockIcon}\n"
"							${signalBars}\n"
"						</div>\n"
"					`\n"
"\n"
"					wifiList.appendChild(wifiItem)\n"
"				})\n"
"			}\n"
"\n"
"			// Open WiFi popup\n"
"			function openWifiPopup(network) {\n"
"				selectedWifi = network\n"
"				const networkName = network.ssid || network.name\n"
"				document.getElementById('popupTitle').textContent = networkName\n"
"\n"
"				if (network.hasPassword) {\n"
"					document.getElementById('popupSubtitle').textContent = 'Nhập mật khẩu để kết nối'\n"
"					document.getElementById('wifiPassword').style.display = 'block'\n"
"					document.getElementById('wifiPassword').focus()\n"
"				} else {\n"
"					document.getElementById('popupSubtitle').textContent = 'Mạng WiFi không có mật khẩu'\n"
"					document.getElementById('wifiPassword').style.display = 'none'\n"
"				}\n"
"\n"
"				document.getElementById('wifiPopup').style.display = 'flex'\n"
"			}\n"
"\n"
"			// Close WiFi popup\n"
"			function closeWifiPopup() {\n"
"				document.getElementById('wifiPopup').style.display = 'none'\n"
"				document.getElementById('wifiPassword').value = ''\n"
"				selectedWifi = null\n"
"			}\n"
"\n"
"			// Connect to WiFi\n"
"			async function connectWifi() {\n"
"				if (selectedWifi) {\n"
"					const password = document.getElementById('wifiPassword').value\n"
"					const networkName = selectedWifi.ssid || selectedWifi.name\n"
"\n"
"					if (selectedWifi.hasPassword && !password) {\n"
"						alert('Vui lòng nhập mật khẩu WiFi')\n"
"						return\n"
"					}\n"
"\n"
"					try {\n"
"						// Send connect request to ESP32\n"
"						const body = 'ssid=' + encodeURIComponent(networkName) + '&pass=' + encodeURIComponent(password)\n"
"						const response = await fetch('/connect', {\n"
"							method: 'POST',\n"
"							headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },\n"
"							body: body,\n"
"						})\n"
"\n"
"						const result = await response.text()\n"
"						document.getElementById('popupSubtitle').textContent = result\n"
"\n"
"                        let a = 0\n"
"						// Poll connection status\n"
"						for (let i = 0; i < 10; i++) {\n"
"							await new Promise((resolve) => setTimeout(resolve, 1000))\n"
"\n"
"							try {\n"
"								const statusResponse = await fetch('/status')\n"
"								const status = await statusResponse.text()\n"
"\n"
"								if (status.indexOf('connected') >= 0) {\n"
"									document.getElementById('popupSubtitle').textContent = 'Đã kết nối!'\n"
"									setTimeout(() => {\n"
"										closeWifiPopup()\n"
"										alert('Đã kết nối wifi kiểm tra đèn tín hiệu!')\n"
"									}, 3000)\n"
"									return\n"
"								}\n"
"\n"
"								document.getElementById('popupSubtitle').textContent = `Đang thử kết nối... (${i + 1}/10)`\n"
"                              a++\n"
"							} catch (statusError) {\n"
"								console.error('Status check failed:', statusError)\n"
"							}\n"
"						}\n"
"\n"
"						// If we get here, connection failed\n"

"						document.getElementById('popupSubtitle').textContent = 'Kết nối thất bại. Vui lòng thử lại.'\n"
"					} catch (error) {\n"
"						console.error('Connect failed:', error)\n"
"						document.getElementById('popupSubtitle').textContent = 'Lỗi kết nối. Vui lòng thử lại.'\n"
"					}\n"
"\n"
"					// Reset button state\n"
"					document.querySelector('.popup-button.connect').textContent = 'Kết nối'\n"
"					document.querySelector('.popup-button.connect').disabled = false\n"
"				}\n"
"			}\n"
"\n"
"			// Close popup when clicking outside\n"
"			document.getElementById('wifiPopup').addEventListener('click', function (e) {\n"
"				if (e.target === this) {\n"
"					closeWifiPopup()\n"
"				}\n"
"			})\n"
"\n"
"			// Handle Enter key in password input\n"
"			document.getElementById('wifiPassword').addEventListener('keypress', function (e) {\n"
"				if (e.key === 'Enter') {\n"
"					connectWifi()\n"
"				}\n"
"			})\n"
"\n"
"			// Initialize the app\n"
"			document.addEventListener('DOMContentLoaded', function () {\n"
"				// Try to scan WiFi networks first\n"
"				scanWifiNetworks()\n"
"			})\n"
"		</script>\n"
"	</body>\n"
"</html>";

// ---------- HTML giao diện cho cấu hình Wi-Fi (mobile friendly) ----------
static const char *html_page =
"<!DOCTYPE html><html><head><meta name='viewport' content='width=device-width,initial-scale=1'>"
"<meta charset='UTF-8'><title>ESP32 WiFi Setup</title>"
"<style>body{font-family:Arial,Helvetica,sans-serif;margin:0;padding:12px;background:#f6f6f6}"
"h2{margin:8px 0} .net{padding:10px;margin:6px 0;background:#fff;border-radius:6px;display:flex;justify-content:space-between;align-items:center}"
"button{padding:8px 12px;border:none;background:#007AFF;color:#fff;border-radius:6px} input{padding:8px;width:100%;box-sizing:border-box;margin-top:6px} #status{margin-top:10px}</style>"
"</head><body>"
"<h2>ESP32 Wi-Fi Setup</h2>"
"<div id=wifiList>Loading networks...</div>"
"<div style='margin-top:10px'>Selected: <span id=sel>None</span></div>"
"<div id=form style='margin-top:10px;display:none'>"
"<input id=pwd type=password placeholder='Password' />"
"<div style='margin-top:8px'><button id=connect>Connect</button></div>"
"</div>"
"<div id=status></div>"
"<script>\n"
"async function scan(){\n"
"  document.getElementById('wifiList').innerText='Scanning...';\n"
"  try{\n"
"    let r=await fetch('/scan');\n"
"    let j=await r.json();\n" 
"    let html='';\n"
"    if(j.length==0) html='<div>No networks found</div>';\n"
"    for(let i=0;i<j.length;i++){\n"
"      let s=j[i].ssid;\n"
"      html+='<div class=\"net\"><span>'+s+'</span><button onclick=\"select(\\''+encodeURIComponent(s)+'\\')\">Select</button></div>';\n"
"    }\n"
"    document.getElementById('wifiList').innerHTML=html;\n"
"  }catch(e){document.getElementById('wifiList').innerText='Scan failed';}\n"
"}\n"
"function select(ssid){\n"
"  document.getElementById('sel').innerText=decodeURIComponent(ssid);\n"
"  document.getElementById('form').style.display='block';\n"
"  window._selected=decodeURIComponent(ssid);\n"
"}\n"
"document.getElementById('connect').addEventListener('click', async ()=>{\n"
"  let ssid=window._selected; let pwd=document.getElementById('pwd').value;\n"
"  document.getElementById('status').innerText='Connecting...';\n"
"  let body='ssid='+encodeURIComponent(ssid)+'&pass='+encodeURIComponent(pwd);\n"
"  try{\n"
"    let r=await fetch('/connect',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body});\n"
"    let t=await r.text();\n"
"    document.getElementById('status').innerText=t;\n"
"    // poll status\n"
"    for(let i=0;i<10;i++){\n"
"      await new Promise(r=>setTimeout(r,1000));\n"
"      let s=await (await fetch('/status')).text();\n"
"      if(s.indexOf('connected')>=0){document.getElementById('status').innerText='Connected!';break}\n"
"      document.getElementById('status').innerText='Trying... ('+(i+1)+')';\n"
"    }\n"
"  }catch(e){document.getElementById('status').innerText='Connect request failed';}\n"
"});\n"
"window.onload=scan;\n"
"</script></body></html>";
